# Generated by Django 5.1.3 on 2024-11-27 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAchievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAchievements_userachievement', to='UserAchievements.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAchievements_userachievement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='achievement',
            table='UserAchievements_achievement',
        ),
        migrations.AlterModelTable(
            name='userachievement',
            table='UserAchievements_userachievement',
        ),
    ]
