# Generated by Django 5.1.1 on 2024-11-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userTrips", "0003_alter_tripdetails_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripdetails",
            name="user_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
