# Generated by Django 5.1.1 on 2024-11-19 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userTrips", "0005_rename_user_email_tripdetails_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripdetails",
            name="stops",
        ),
        migrations.DeleteModel(
            name="TripStop",
        ),
    ]
