# Generated by Django 5.1.1 on 2024-11-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userExpenses", "0003_initial"),
        ("userTrips", "0006_remove_tripdetails_stops_delete_tripstop"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="userTrips.tripdetails",
            ),
        ),
    ]
