# Generated by Django 5.1.1 on 2024-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userExpenses", "0004_expense_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="trip",
        ),
        migrations.AddField(
            model_name="expense",
            name="trip_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
