# Generated by Django 5.1.1 on 2024-11-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userExpenses", "0006_alter_expense_trip_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="trip_name",
            field=models.CharField(default="Trip", max_length=100),
        ),
    ]
